---
title: "Evaluating the role of model structure in the predictive performance of European COVID-19 forecasts"
format: html
---

Katharine Sherratt (1), Rok Grah (2), Bastian Prasse (2), Friederike Becker (3), Jamie McLean (1), Sam Abbott (1), Sebastian Funk (1)

(1) Centre for Mathematical Modelling of Infectious Diseases, London School of Hygiene & Tropical Medicine
(2) European Centre for Disease Prevention and Control
(3) Institute of Statistics, Karlsruhe Institute of Technology

Email: katharine.sherratt@lshtm.ac.uk

### Abstract

{{< include quarto/_abstract.qmd >}}

## Main text

### Background

::: {.callout-caution collapse="true" title="TODO"}
- [ ] update all references
:::

{{< include quarto/_background.qmd >}}

### Methods

::: {.callout-caution collapse="true" title="TODO"}
- [ ] joint model to include cases/deaths (include results in supp)
- [ ] list the many model specs we tried in the supplement
- [ ] check mean average WIS over time and by other confounders
- [ ] natural scale fit with gamma dist
:::

{{< include quarto/_methods.qmd >}}

### Results

::: {.callout-caution collapse="true" title="TODO"}
- [ ] Figure 1 edit for clarity; use cohort mean performance over time?
- [ ] table 2 check adjusted numbers
- [ ] table 2 include adjustment set in caption
:::

{{< include quarto/_results.qmd >}}

### Discussion
::: {.callout-caution collapse="true" title="TODO"}
- [ ] note should/could use proportional methods from survival analysis
:::

{{< include quarto/_discussion.qmd >}}

### References

::: {.callout-caution collapse="true" title="TODO"}
- [ ] sync with google doc zotero to bib file
:::

{{< include quarto/_references.qmd >}}

## Supplement

::: {.callout-caution collapse="true" title="TODO"}
- [ ] check supplement includes natural scale results
- [ ] include univariate associations of all variables
:::

{{< include quarto/supplement/_supplement.qmd >}}
