# Notebook

TODO bugs

Codebase structure

- [x] use separate quarto docs in /report for: abstract, background, methods, results, discussion, supplement
- [x] combine in a full quarto manuscript using \_includes
- [ ] Update CLAUDE.md to reflect structural changes

Code functionality

- [x] check results pipeline runs
- [ ] check the figures against rev comments
- [x] fix variant code and data issues

Reporting

- [ ] Add mathematical notation for the model in the main text, with explanation
- [ ] write an abstract based on Research-narrative.qmd
- [ ] assess whether the flow of text matches with intended research narrative

Admin

- [ ] flag remaining reviewer comments and suggest actions
- [ ] refactor inline referencing with zotero citation keys (https://www.zotero.org/kathsherratt/library)

TODO features

- [x] normalise by population before scoring #pr-148
- [x] remove geographic specificity as an exposure, add geographic specificity as -confounder-
- [ ] add choice of one OR both case/death as -counfounder- (rationale: not independent; "were modellers for death targets also accounting for cases")
- [x] create a DAG to represent modelling approach, include in supplement
- [ ] use a schematic in the main text to demonstrate approach

Future work (See: future-work.qmd)

- [ ] correlation matrix: is each model's error most correlated with the mean error of its own class?
- [ ] use a simulation approach
- [ ] expand to cover all forecast challenges
- [ ] repeated measures stats (intraclass correlation)
- [ ] hazards models
- [ ] matched cohort: select a 'control' baseline forecaster of each type (timeseries, mechanistic)

## notes

- refer to brockhaus 2023:

- > To evaluate betweenmethod agreement, we reproduce the estimates generated by different groups using a variety of statistical approaches, standardizing analytical choices to assess how they contribute to the observed disagreement.
  > These analytical choices include the data source, data preprocessing, assumed generation time distribution, statistical tuning parameters, and various delay distributions.
  > We find that in practice, these auxiliary choices in the estimation of Rt may affect results at least as strongly as the selection of the statistical approach.
  > They should thus be communicated transparently along with the estimates.

### 28 April 2026

- [propensity] match scores by similarity of forecast target?

### 2 April 2026

- are there any examples of simpson's paradox where the ensemble changes direction from all component forecasts?
- forecast trend vs observed trend / rate of change (aka log)
- Cramer distance among models
- predicting performance of ensemble based on size; bias-variance
- What's driving the WIS?
  Exploring the WIS as a composite score
- use model contributors...
  - orcID or author lookup, volume of publications/citations, as indicator of ... expertise
  - number per team as indicator of resources
