# Notebook

TODO

Codebase and manuscript structure
- [ ] convert full manuscript into quarto
    - [ ] incorporate results.qmd so all main output is in a single document; either copy in results directly, or use quarto _includes if that compromises readability
    - [ ] Update CLAUDE.md to reflect structural changes

Code functionality
- [ ] check results pipeline runs
- [ ] update the figures
- [x] fix variant code and data issues

Reporting 
- [ ] create paragraph-by-paragraph one line summary in the `Research-narrative.md`
    - [ ] assess whether the flow of text matches with intended research narrative
    - [ ] compare the text against the STROBE reporting guidelines and flag issues: https://resources.equator-network.org/reporting-guidelines/strobe/#summary 
- [ ] Add mathematical notation for the model in the main text, with explanation

new features:
- [x] normalise by population before scoring
- [ ] create a DAG to represent modelling approach
- [ ] remove geographic specificity as an exposure
- [ ] add geographic specificity as an interaction
- [ ] consider identifying the simplest possible version of such a model that can be used to demonstrate the approach, and then build up to the more complex version
- [ ] repeated measures stats.

admin:
- [ ] flag remaining reviewer comments and suggest actions
- [ ] refactor inline referencing with zotero citation keys (https://www.zotero.org/kathsherratt/library)

## notes

### 2 April 2026
- are there any examples of simpson's paradox where the ensemble changes direction from all component forecasts?
- forecast trend vs observed trend / rate of change (aka log)
- Cramer distance among models
- predicting performance of ensemble based on size; bias-variance
- What's driving the WIS? Exploring the WIS as a composite score
- use model contributors...
    - orcID or author lookup, volume of publications/citations, as indicator of ... expertise
    - number per team as indicator of resources
