# Notebook

TODO

- [ ] Update CLAUDE.md to reflect structural changes
- [ ] Plan to address issue 159 in a PR.
  this should include sequential commits to:
  - plotting the distribution of the outcome (wis), as read in by m.data
  - checking distributions to better account for skew: gamma; tweedie
  - changing the model family in the code
  - re-running results saved as a new object
  - plotting the fit and the residuals in direct comparison with former results
  - any metrics to check the fit
  - rendering the whole manuscript again
  - commit, push the branch
  - documenting the choice and comparison in the supplement, linking to that model fitting commit

## notes

- refer to brockhaus 2023:

- > To evaluate betweenmethod agreement, we reproduce the estimates generated by different groups using a variety of statistical approaches, standardizing analytical choices to assess how they contribute to the observed disagreement.
  > These analytical choices include the data source, data preprocessing, assumed generation time distribution, statistical tuning parameters, and various delay distributions.
  > We find that in practice, these auxiliary choices in the estimation of Rt may affect results at least as strongly as the selection of the statistical approach.
  > They should thus be communicated transparently along with the estimates.

### 24 July 2026

### 28 April 2026

- [propensity] match scores by similarity of forecast target?

### 2 April 2026

- are there any examples of simpson's paradox where the ensemble changes direction from all component forecasts?
- forecast trend vs observed trend / rate of change (aka log)
- Cramer distance among models
- predicting performance of ensemble based on size; bias-variance
- What's driving the WIS?
  Exploring the WIS as a composite score
- use model contributors...
  - orcID or author lookup, volume of publications/citations, as indicator of ... expertise
  - number per team as indicator of resources
