---
title: "Model building"
format: html
---

In developing this analysis we produced two substantive versions.
The first (version 1) was developed over 2023-24 and published as a pre-print.
We substantially revised this work in order to develop a more robust theoretical framework that clarified factors affecting the forecast estimate or forecast estimand.

In this process, we considered a range of model specifications.
We note these decisions here for completeness and reproducible evaluation.
A record of model development is also shown in the code history committed to: [analysis-model.R](https://github.com/epiforecasts/eval-by-method/commits/main/R/analysis-model.R).

## Covariate selection

We used a fully prior-driven approach to selecting covariates.
In version 1 we specified a framework for influences on forecast performance based on co-authors' domain expertise, and data availability.
At no point did we use quantitative measures of statistical effect to select covariates.
In version 2 we further clarified this approach using a directed acyclic graph.

|   | Version 1 (code) | Version 2 (code) |
|----|----|----|
|  |  |  |
|  |  |  |
| Epidemiological outcome (cases / deaths) | Originally not included within the model; all data were stratified by outcome and models fitted separately. | We considered epi outcome as a factor of the forecast estimand, and included as a fixed effect covariate |
|  |  |  |

## Model fitting

We report issues and decisions made in model fitting for version 2.

+--------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| Fitting variation                                                        | Effect                                                                                                        | Decision                                                                                                                                     | Code (version 2)                                                                                                                              |
+==========================================================================+===============================================================================================================+==============================================================================================================================================+===============================================================================================================================================+
| Gaussian family                                                          |                                                                                                               |                                                                                                                                              | [Version 2](https://github.com/epiforecasts/eval-by-method/blob/6752220d5b9c0eee1186cb96435ec35985e8d7c8/R/analysis-model.R)                  |
+--------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| Using an identity or a log link                                          | No qualitative difference in residual skew; no difference in main effect results                              | Kept the log link                                                                                                                            | [commit](https://github.com/epiforecasts/eval-by-method/blob/6752220d5b9c0eee1186cb96435ec35985e8d7c8/R/sensitivity/check-link-robustness.R)  |
+--------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| Log transform the WIS and use a Gaussian distribution with identity link | log(WIS) is near-symmetric, and residual skew/kurtosis improve markedly; no difference in main effect results | We rejected this on the basis that (1) the scores are no longer "proper"; (2) interpretability (avoiding a log transform of a log transform) | [commit](https://github.com/epiforecasts/eval-by-method/blob/6752220d5b9c0eee1186cb96435ec35985e8d7c8/R/sensitivity/model-logresp.R)          |
+--------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                          |                                                                                                               |                                                                                                                                              |                                                                                                                                               |
+--------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+