name: render-report

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  render-report:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Compile the report
        run: |
          rmarkdown::render("output/results.Rmd")
        shell: Rscript {0}

      - name: Create Pull Request
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update rendered report"
          title: "Update rendered report"
          body: "This is an automated pull request to update the rendered report."
          branch: "render-report-${{ github.run_number }}"
          labels: "documentation"
          reviewers: kathsherratt,sbfnk
          add-paths: |
            output/results.pdf
          token: ${{ secrets.GITHUB_TOKEN }}
